"""Add email field; add index

Revision ID: 018047731c3a
Revises: f3664672dd66
Create Date: 2023-11-26 19:30:49.212259

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "018047731c3a"
down_revision = "f3664672dd66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_user",
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=True
        ),
    )
    op.alter_column("user_user", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("user_user_username_key", "user_user", type_="unique")
    op.create_index(op.f("ix_user_user_email"), "user_user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_user_username"), "user_user", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_user_username"), table_name="user_user")
    op.drop_index(op.f("ix_user_user_email"), table_name="user_user")
    op.create_unique_constraint("user_user_username_key", "user_user", ["username"])
    op.alter_column("user_user", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user_user", "email")
    # ### end Alembic commands ###
