"""initial commit

Revision ID: 19bfa79b903c
Revises: 
Create Date: 2024-02-24 13:51:11.507624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '19bfa79b903c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('true', name='username_or_email_required'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_user_email'), 'user_user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_username'), 'user_user', ['username'], unique=True)
    op.create_table('match',
    sa.Column('user_1_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_2_uuid', sa.Uuid(), nullable=True),
    sa.Column('is_match', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_1_uuid'], ['user_user.uuid'], ),
    sa.ForeignKeyConstraint(['user_2_uuid'], ['user_user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_index(op.f('ix_user_user_username'), table_name='user_user')
    op.drop_index(op.f('ix_user_user_email'), table_name='user_user')
    op.drop_table('user_user')
    # ### end Alembic commands ###
