"""Added date_created for user

Revision ID: 341a94b15e6f
Revises: e2384572475f
Create Date: 2023-09-30 10:46:02.659917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "341a94b15e6f"
down_revision = "e2384572475f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_user", sa.Column("date_created", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_user", "date_created")
    # ### end Alembic commands ###
